import {
  ApiError,
  type Transport,
  type TransportResponse,
} from "@api-zero/core";

/** One recorded attempt, as the demo timeline shows it. */
export interface Attempt {
  /** 1-based, matching what `onRetry` reports. */
  number: number;
  /** Milliseconds since the call started, when this attempt reached the wire. */
  at: number;
  /** When its response came back. The wait is the gap to the next `at`. */
  respondedAt: number;
  status: number;
  /** Present when the server dictated the wait. */
  retryAfter?: number;
}

export interface FakeTransportOptions {
  /** How many attempts fail before one succeeds. */
  failures: number;
  /** The status those failures carry. */
  status: number;
  /** Seconds to advertise in `Retry-After`, when the status is 429 or 503. */
  retryAfter?: number;
  /** Round trip time to simulate, so the timeline is not instant. */
  latency?: number;
  onAttempt(attempt: Attempt): void;
}

/**
 * A transport that fails a fixed number of times and then succeeds.
 *
 * `Transport` is one method, which is what makes this possible: the retry
 * policy, the backoff, the jitter and the `Retry-After` handling all run for
 * real above it. Only the wire is fake, so the timings a reader watches are the
 * ones their own application would get.
 *
 * The alternative — pointing the demo at a public echo service — makes the
 * library look broken every time that service is down or rate-limits the
 * reader, and gives no way to ask for a 429 on demand.
 */
export function createFakeTransport(options: FakeTransportOptions): Transport {
  const { failures, status, retryAfter, latency = 120, onAttempt } = options;
  const startedAt = Date.now();
  let attempt = 0;

  return {
    async send(context): Promise<TransportResponse> {
      attempt += 1;
      const number = attempt;
      const at = Date.now() - startedAt;

      await new Promise<void>((resolve, reject) => {
        const timer = setTimeout(resolve, latency);
        // A transport that ignores the signal leaves the caller waiting for a
        // request they already abandoned, and the demo would misreport how
        // cancellation behaves.
        context.signal?.addEventListener(
          "abort",
          () => {
            clearTimeout(timer);
            reject(context.signal?.reason ?? new Error("Aborted"));
          },
          { once: true },
        );
      });

      const failing = number <= failures;
      const sendsRetryAfter =
        failing &&
        retryAfter !== undefined &&
        (status === 429 || status === 503);

      onAttempt({
        number,
        at,
        respondedAt: Date.now() - startedAt,
        status: failing ? status : 200,
        retryAfter: sendsRetryAfter ? retryAfter : undefined,
      });

      if (failing) {
        // Thrown, not returned. A transport owns the decision about what counts
        // as a failure — `FetchTransport` throws on `!response.ok` and the
        // client never re-checks the status. A custom transport that returns a
        // 500 in a `TransportResponse` reports success, and the retry policy
        // never sees anything to retry.
        throw ApiError.from(
          status === 429 ? "Too Many Requests" : "Server Error",
          {
            status,
            statusText: status === 429 ? "Too Many Requests" : "Server Error",
            request: context,
            attempt: number,
            data: { error: "generated by the documentation" },
            // A real `Response`, because `respectRetryAfter` reads the header
            // off `error.response` rather than off the error itself.
            response: sendsRetryAfter
              ? new Response(null, {
                  status,
                  headers: { "retry-after": String(retryAfter) },
                })
              : undefined,
          },
        );
      }

      return {
        status: 200,
        statusText: "OK",
        headers: { "content-type": "application/json" },
        data: { id: 1, name: "Ada" },
      };
    },
  };
}
